server:
  port: 8050

spring:
  application:
    name: websocket-server
  data:
    redis:
      host: 127.0.0.1
      password:
      port: 6379
      database: 1
      jedis:
        pool:
          max-active: 16  # 最大连接数
          max-idle: 4     # 最大空闲连接数
          min-idle: 0     # 最小空闲连接数
          max-wait: 1ms   # 连接池最大阻塞时间